name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Prod
    permissions:
      id-token: write
      pages: write
    steps:
      # Setup
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install dependencies
        run: npm install && curl -fsSL https://get.pulumi.com | sh

      # Build
      - name: Build
        run: npm run build:prod

      # Backend
      - name: Deploy Backend
        run: npm run deploy -- JS-Puzzles/prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # Frontend
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload frontend assets
        uses: actions/upload-pages-artifact@v2
        with:
          path: "packages/frontend/dist"
      - name: Deploy Frontend (GitHub Pages)
        id: deployment
        uses: actions/deploy-pages@v2
